<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="css/estilo.css">
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-1 col-lg-1 d-md-block sidebar">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="agenda.phtml">
                            <i class="bi bi-calendar"></i> Agenda
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="novo_doutor.phtml">
                            <i class="bi bi-person-fill"></i> Doutor
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="novo_paciente.phtml">
                            <i class="bi bi-people-fill"></i> Paciente
                        </a>
                    </li>
                    </ul>
            </div>
        </nav>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>