<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pacientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="css/estilo.css">
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 col-lg-2 d-md-block sidebar">
            <div class="position-sticky">
                <ul class="nav flex-column">

                    <li class="nav-item">
                        <a class="nav-link" href="agenda.phtml">
                            <i class="bi bi-calendar fs-5"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="novo_doutor.phtml">
                            <i class="bi bi-person-fill fs-5"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="bi bi-people-fill fs-5"></i>
                        </a>
                    </li>

                </ul>
            </div>
        </nav>

        <main class="col-md-9 col-lg-11 main-content">
             <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Pacientes</h1>
                <button type="button" class="btn btn-primary d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                    <i class="bi bi-plus me-1"></i> Adicionar Paciente
                </button>
            </div>
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Ian Derick</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </button>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Bruna Prochnow</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <a href="#" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Andrea Silmara</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <a href="#" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </div> 
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Ivan Rodrigues</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <a href="#" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </div> 
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Caio Santos</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoPaciente">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <a href="#" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </div>    
        </main>
    </div>
</div>

<div class="modal fade" id="modalNovoPaciente" tabindex="-1" aria-labelledby="modalNovoPacienteLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalNovoPacienteLabel">Novo Paciente</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="#" method="post">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="mb-3">
                                <label for="nomePaciente" class="form-label">Nome:</label>
                                <input type="text" class="form-control" id="nomePaciente" name="nomePaciente" required>
                            </div>
                            <div class="mb-3">
                                <label for="emailPaciente" class="form-label">E-mail:</label>
                                <input type="email" class="form-control" id="emailPaciente" name="emailPaciente" required>
                            </div>
                            <div class="mb-3">
                                <label for="telefonePaciente" class="form-label">Telefone:</label>
                                <input type="tel" class="form-control" id="telefonePaciente" name="telefonePaciente">
                            </div>
                        </div>
                        <div class="col-md-3 text-center">
                            <div class="mb-3">
                                <i class="bi bi-person-circle display-1 text-secondary"></i>
                                <small class="d-block mt-2">Nome:</small>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" form="formNovoPaciente" class="btn btn-green">Salvar</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>