<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doutores</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="css/estilo.css">
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-1 col-lg-1 d-md-block sidebar">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="agenda.phtml">
                            <i class="bi bi-calendar fs-5"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="bi bi-person-fill fs-5"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="novo_paciente.phtml">
                            <i class="bi bi-people-fill fs-5"></i>
                        </a>
                    </li>
                    </ul>
            </div>
        </nav>

        <main class="col-md-9 col-lg-11 px-md-4 main-content">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Doutores</h1>
                <button type="button" class="btn btn-primary d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#modalNovoDoutor">
                    <i class="bi bi-plus me-1"></i> Adicionar Doutor
                </button>
            </div>
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Dr. Bruno</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoDoutor">
                    <i class="bi bi-pencil"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </button>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center list-item pt-10 pb-2 mb-3 border-bottom">
                <span>Dra. Rafaela</span>
                <div class="button-group">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalNovoDoutor">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <a href="#" class="btn btn-danger btn-sm ms-2">
                        <i class="bi bi-trash"></i>
                    </a>
                </div>
            </div>
        </main>
    </div>
</div>

<div class="modal fade" id="modalNovoDoutor" tabindex="-1" aria-labelledby="modalNovoDoutorLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalNovoDoutorLabel">Novo Doutor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="#" method="post">
                    <div class="mb-3">
                        <label for="nomeDoutor" class="form-label">Nome:</label>
                        <input type="text" class="form-control" id="nomeDoutor" name="nomeDoutor" required>
                    </div>
                    <div class="mb-3">
                        <label for="emailDoutor" class="form-label">E-mail:</label>
                        <input type="email" class="form-control" id="emailDoutor" name="emailDoutor" required>
                    </div>
                    <div class="mb-3">
                        <label for="senhaDoutor" class="form-label">Senha:</label>
                        <input type="password" class="form-control" id="senhaDoutor" name="senhaDoutor" required>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="alterarSenha" name="alterarSenha">
                        <label class="form-check-label" for="alterarSenha">Alterar senha no próximo login?</label>
                    </div>
                    <div class="mb-3">
                        <label for="corDoutor" class="form-label">Cor do Doutor</label>
                        <input type="color" class="form-control form-control-color" id="corDoutor" name="corDoutor">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" form="formNovoDoutor" class="btn btn-green">Salvar</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>